### ISSUE TITLE
Plugin always return could not create config file

### ISSUE THREAD

**Issue by obelouix** [obelouix/ObelouixEssential-For-Sponge#1]
```
========================
!!                    !!
!!  MINECRAFT server  !!
!!                    !!
========================


starting server


[22:27:12] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftfo
rge.fml.common.launcher.FMLServerTweaker
[22:27:12] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minec
raftforge.fml.common.launcher.FMLServerTweaker
[22:27:12] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.f
ml.common.launcher.FMLServerTweaker
[22:27:13] [main/INFO] [FML]: Forge Mod Loader version 8.99.171.1480 for Minecra
ft 1.8 loading
[22:27:13] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version
 1.8.0_45, running on Windows 7:amd64:6.1, installed at C:\Program Files\Java\jr
e1.8.0_45
[22:27:13] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.Mixin
Tweaker from sponge-1.8-1446-2.1DEV-494.jar
[22:27:13] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftfo
rge.fml.common.launcher.FMLInjectionAndSortingTweaker
[22:27:13] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepower
ed.asm.launch.MixinTweaker
[22:27:13] [main/INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.4.4 Sour
ce=file:/E:/Users/Louis/Documents/GitHub/Serveur/Sponge/mods/sponge-1.8-1446-2.1
DEV-494.jar Env=SERVER
[22:27:13] [main/INFO] [mixin]: Adding new token provider org.spongepowered.mod.
SpongeCoremod$TokenProvider to MixinEnvironment[PREINIT]
[22:27:13] [main/INFO] [mixin]: Adding new token provider org.spongepowered.mod.
SpongeCoremod$TokenProvider to MixinEnvironment[DEFAULT]
[22:27:13] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftfo
rge.fml.common.launcher.FMLDeobfTweaker
[22:27:13] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.f
ml.common.launcher.FMLInjectionAndSortingTweaker
[22:27:13] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.f
ml.common.launcher.FMLInjectionAndSortingTweaker
[22:27:13] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.f
ml.relauncher.CoreModManager$FMLPluginWrapper
[22:27:14] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certi
ficate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[22:27:14] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.f
ml.relauncher.CoreModManager$FMLPluginWrapper
[22:27:14] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.as
m.launch.MixinTweaker
[22:27:14] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.f
ml.common.launcher.FMLDeobfTweaker
[22:27:14] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftfo
rge.fml.common.launcher.TerminalTweaker
[22:27:14] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepower
ed.asm.mixin.MixinEnvironment$EnvironmentStateTweaker
[22:27:14] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.f
ml.common.launcher.TerminalTweaker
[22:27:14] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.as
m.mixin.MixinEnvironment$EnvironmentStateTweaker
[22:27:16] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecra
ft.server.MinecraftServer}
[22:27:19] [Server thread/INFO]: Starting minecraft server version 1.8
[22:27:19] [Server thread/INFO] [MinecraftForge]: Attempting early MinecraftForg
e initialization
[22:27:19] [Server thread/INFO] [FML]: MinecraftForge v11.14.3.1480 Initialized
[22:27:19] [Server thread/INFO] [FML]: Replaced 204 ore recipies
[22:27:20] [Server thread/INFO] [MinecraftForge]: Completed early MinecraftForge
 initialization
[22:27:20] [Server thread/INFO] [FML]: Found 0 mods from the command line. Injec
ting into mod discoverer
[22:27:20] [Server thread/INFO] [FML]: Searching E:\Users\Louis\Documents\GitHub
\Serveur\Sponge\mods for mods
[22:27:21] [Server thread/INFO] [FML]: Forge Mod Loader has identified 5 mods to
 load
[22:27:21] [Server thread/INFO] [FML]: Attempting connection with missing mods [
mcp, FML, Forge, Sponge, ObelouixEssentialSponge] at CLIENT
[22:27:21] [Server thread/INFO] [FML]: Attempting connection with missing mods [
mcp, FML, Forge, Sponge, ObelouixEssentialSponge] at SERVER
[22:27:21] [Server thread/INFO] [FML]: Processing ObjectHolder annotations
[22:27:21] [Server thread/INFO] [FML]: Found 384 ObjectHolder annotations
[22:27:21] [Server thread/INFO] [FML]: Identifying ItemStackHolder annotations
[22:27:21] [Server thread/INFO] [FML]: Found 0 ItemStackHolder annotations
[22:27:21] [Server thread/INFO] [FML]: Configured a dormant chunk cache size of
0
[22:27:22] [Server thread/INFO] [FML]: Applying holder lookups
[22:27:22] [Server thread/INFO] [FML]: Holder lookups applied
[22:27:22] [Server thread/INFO] [FML]: Injecting itemstacks
[22:27:22] [Server thread/INFO] [FML]: Itemstack injection complete
[22:27:22] [Server thread/INFO]: Loading properties
[22:27:22] [Server thread/INFO]: Default game type: SURVIVAL
[22:27:22] [Server thread/INFO]: Generating keypair
[22:27:22] [Server thread/INFO]: Starting Minecraft server on *:25565
[22:27:22] [Server thread/INFO] [FML]: Injecting itemstacks
[22:27:22] [Server thread/INFO] [FML]: Itemstack injection complete
[22:27:22] [Server thread/INFO] [FML]: Forge Mod Loader has successfully loaded
5 mods
[22:27:22] [Server thread/INFO] [STDOUT]: [org.spongepowered.common.world.Dimens
ionManager:init:52]: Proxying to Forge DimensionManager Init!
[22:27:22] [Server thread/INFO]: Preparing level "world"
[22:27:22] [Server thread/INFO] [FML]: Injecting existing block and item data in
to this server instance
[22:27:22] [Server thread/INFO] [FML]: Applying holder lookups
[22:27:22] [Server thread/INFO] [FML]: Holder lookups applied
[22:27:23] [Server thread/INFO] [FML]: Loading dimension 0 (world) (net.minecraf
t.server.dedicated.DedicatedServer@79a649e9)
[22:27:23] [Server thread/INFO] [FML]: Loading dimension 1 (DIM1) (net.minecraft
.server.dedicated.DedicatedServer@79a649e9)
[22:27:23] [Server thread/INFO] [FML]: Loading dimension -1 (DIM-1) (net.minecra
ft.server.dedicated.DedicatedServer@79a649e9)
[22:27:23] [Server thread/INFO]: Preparing start region for level -1
[22:27:24] [Server thread/INFO]: Preparing start region for level 1
[22:27:24] [Server thread/INFO]: Done (1,463s)! For help, type "help" or "?"
[22:27:24] [Server thread/ERROR] [ObelouixEssentialSponge]: Could not create mai
n config file 'ObelouixConfig.conf'
[22:27:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]: java.io.IOException: Le chemin dÆaccÞs spÚcifiÚ est introuvable
[22:27:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at java.io.WinNTFileSystem.createFileExclusively(Native Method)
[22:27:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at java.io.File.createNewFile(Unknown Source)
[22:27:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at fr.obelouix.Essentials.ObelouixEssential.onEnable(ObelouixEss
ential.java:80)
[22:27:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:27:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[22:27:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Sourc
e)
[22:27:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at java.lang.reflect.Method.invoke(Unknown Source)
[22:27:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at org.spongepowered.mod.plugin.SpongeModPluginContainer.handleM
odStateEvent(SpongeModPluginContainer.java:126)
[22:27:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:27:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[22:27:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Sourc
e)
[22:27:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at java.lang.reflect.Method.invoke(Unknown Source)
[22:27:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at com.google.common.eventbus.EventSubscriber.handleEvent(EventS
ubscriber.java:74)
[22:27:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at com.google.common.eventbus.SynchronizedEventSubscriber.handle
Event(SynchronizedEventSubscriber.java:47)
[22:27:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at com.google.common.eventbus.EventBus.dispatch(EventBus.java:32
2)
[22:27:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at com.google.common.eventbus.EventBus.dispatchQueuedEvents(Even
tBus.java:304)
[22:27:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[22:27:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at net.minecraftforge.fml.common.LoadController.sendEventToModCo
ntainer(LoadController.java:212)
[22:27:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at net.minecraftforge.fml.common.LoadController.propogateStateMe
ssage(LoadController.java:190)
[22:27:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:27:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[22:27:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Sourc
e)
[22:27:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at java.lang.reflect.Method.invoke(Unknown Source)
[22:27:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at com.google.common.eventbus.EventSubscriber.handleEvent(EventS
ubscriber.java:74)
[22:27:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at com.google.common.eventbus.SynchronizedEventSubscriber.handle
Event(SynchronizedEventSubscriber.java:47)
[22:27:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at com.google.common.eventbus.EventBus.dispatch(EventBus.java:32
2)
[22:27:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at com.google.common.eventbus.EventBus.dispatchQueuedEvents(Even
tBus.java:304)
[22:27:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[22:27:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at net.minecraftforge.fml.common.LoadController.distributeStateM
essage(LoadController.java:119)```
[22:27:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at net.minecraftforge.fml.common.Loader.serverStarting(Loader.ja
va:781)
[22:27:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at net.minecraftforge.fml.common.FMLCommonHandler.handleServerSt
arting(FMLCommonHandler.java:319)
[22:27:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(D
edicatedServer.java:286)
[22:27:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java
:438)
[22:27:24] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStrea
m:println:-1]:  at java.lang.Thread.run(Unknown Source)

**Comment by obelouix** [comment]
corrected , it was just a mistake in the code
